CREATE TABLE `perkara` (
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `jenis_acara` char(1) DEFAULT NULL,
    `alur_perkara_id` int(11) unsigned NOT NULL COMMENT 'Id Alur Perkara: merujuk ke tabel alur_perkara kolom id(by system)',
    `tanggal_pendaftaran` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran: isian tanggal',
    `jenis_perkara_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Jenis Perkara: merujuk ke tabel jenis_perkara kolom id',
    `jenis_perkara_kode` varchar(20) DEFAULT '' COMMENT 'Kode Jenis Perkara: merujuk ke tabel jenis_perkara kolom kode (by system)',
    `jenis_perkara_nama` varchar(100) DEFAULT '' COMMENT 'Nama Jenis Perkara: merujuk ke tabel jenis_perkara kolom nama (by system)',
    `jenis_perkara_text` varchar(400) DEFAULT '' COMMENT 'Nama Jenis Perkara lengkap dengan induk perkaranya(by system)',
    `nomor_urut_register` int(11) unsigned DEFAULT NULL COMMENT 'Nomor Urut Buku Register: Reset per bulan',
    `nomor_urut_perkara` int(11) unsigned DEFAULT NULL COMMENT 'Nomor Urut Perkara: reset per tahun untuk tiap alur_perkara_id (manual/by system)',
    `nomor_perkara` varchar(250) NOT NULL COMMENT 'Nomor Perkara: (manual/by system)',
    `nomor_indeks` varchar(250) DEFAULT NULL COMMENT 'Nomor Indeks Perkara: untuk keperluan pengurutan data berdasarkan tahun,alur perkara dan nomor urut perkara (by system)',
    `tanggal_surat` date DEFAULT NULL COMMENT 'Tanggal Surat Gugatan/Permohonan/Pelimpahan: isian tanggal',
    `nomor_surat` varchar(150) DEFAULT '' COMMENT 'Nomor Surat Gugatan/Permohonan/Pelimpahan: isian bebas',
    `surat_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Surat Gugatan/Permohonan/Pelimpahan: form upload',
    `pihak1_text` longtext COMMENT 'Penggugat/Pemohon/Penuntut: (by system)',
    `pengacara_pihak1` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak2_text` longtext COMMENT 'Tergugat/Termohon/Terdakwa: (by system)',
    `pengacara_pihak2` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak3_text` longtext COMMENT 'Pihak Ke Tiga yang melakukan Intervensi: (by system)',
    `pengacara_pihak3` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak4_text` longtext,
    `pengacara_pihak4` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `para_pihak` longtext,
    `pihak_dipublikasikan` char(1) DEFAULT 'Y' COMMENT 'Para Pihak Dipublikasikan: pilihan(Y=Ya; T=Tidak)',
    `posita` longtext CHARACTER SET utf8mb4,
    `petitum` longtext CHARACTER SET utf8mb4,
    `petitum_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Petitum: form upload',
    `nomor_dakwaan` varchar(150) DEFAULT NULL,
    `tanggal_dakwaan` date DEFAULT NULL,
    `dakwaan` longtext CHARACTER SET utf8mb4,
    `pasal_dakwaan` longtext,
    `dakwaan_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Dakwaan: form upload',
    `tanggal_rencana_perdamaian` date DEFAULT NULL COMMENT 'Tanggal Penerimaan Rencana Perdamaian: isian tanggal',
    `tanggal_pengesahan_perdamaian` date DEFAULT NULL COMMENT 'Tanggal Pengesahan Perdamaian: isian tanggal',
    `tanggal_penyelesaian_mediasi` date DEFAULT NULL COMMENT 'Tanggal Penyelesaian Mediasi: isian tanggal',
    `tanggal_penyelesaian_konsiliasi` date DEFAULT NULL COMMENT 'Tanggal Penyelesaian Konsiliasi: isian tanggal',
    `perkara_rujukan_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara Rujukan: merujuk ke tabel perkara kolom perkara_id',
    `nomor_perkara_rujukan` varchar(50) DEFAULT '' COMMENT 'Nomor Perkara yang menjadi rujukan: merujuk ke tabel perkara kolom nomor_perkara (by system)',
    `tanggal_pendaftaran_rujukan` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran Rujukan: merujuk ke tabel perkara kolom tanggal_pendaftaran (by system)',
    `catatan_pendaftaran` text COMMENT 'Catatan Pendaftaran: isian bebas',
    `prodeo` tinyint(1) DEFAULT '0' COMMENT 'Status Prodeo: 0=Tidak,1:Ya',
    `terdakwa_anak` tinyint(1) DEFAULT '0' COMMENT 'Terdakwa Anak-Anak: 0 Tidak 1=Ya',
    `tahapan_terakhir_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Tahapan Proses: merujuk ke tabel tahapan_proses kolom id (by system)',
    `tahapan_terakhir_text` varchar(50) DEFAULT '' COMMENT 'Nama Tahapan Terakhir: merujuk ke tabel tahapan_proses kolom nama (by system)',
    `proses_terakhir_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Proses Perkara Terakhir: menujuk ke tabel proses kolom id (by system)',
    `proses_terakhir_text` varchar(200) DEFAULT '' COMMENT 'Proses Perkara Terakhir: menujuk ke tabel proses kolom Nama(by system)',
    `nilai_sengketa` bigint(20) unsigned DEFAULT '0',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT '' COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT '' COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`perkara_id`),
    UNIQUE KEY `nomor_perkara` (`nomor_perkara`),
    KEY `jenis_perkara_id` (`jenis_perkara_id`),
    KEY `nomor_indeks` (`nomor_indeks`),
    KEY `alur_perkara_id` (`alur_perkara_id`),
    KEY `tanggal_pendaftaran` (`tanggal_pendaftaran`),
    KEY `tahapan_terakhir_id` (`tahapan_terakhir_id`),
    KEY `proses_terakhir_id` (`proses_terakhir_id`),
    KEY `diinput_tanggal` (`diinput_tanggal`),
    KEY `diperbaharui_tanggal` (`diperbaharui_tanggal`),
    CONSTRAINT `perkara_fk` FOREIGN KEY (`alur_perkara_id`) REFERENCES `alur_perkara` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Induk Perkara'


CREATE TABLE `perkara_akta_cerai` (
    `perkara_id` bigint(20) unsigned NOT NULL,
    `tahun_akta_cerai` int(11) DEFAULT NULL,
    `nomor_urut_akta_cerai` int(11) DEFAULT NULL,
    `nomor_akta_cerai` varchar(50) DEFAULT NULL,
    `tgl_akta_cerai` date DEFAULT NULL,
    `no_seri_akta_cerai` varchar(50) DEFAULT NULL,
    `jenis_cerai` varchar(50) DEFAULT NULL,
    `faktor_perceraian_id` int(11) DEFAULT NULL,
    `qobla_bada` tinyint(4) DEFAULT NULL,
    `perceraian_ke` int(11) DEFAULT NULL,
    `keadaan_istri` tinyint(4) DEFAULT NULL,
    `tgl_penyerahan_akta_cerai` date DEFAULT NULL,
    `tgl_penyerahan_akta_cerai_pihak2` date DEFAULT NULL,
    `akta_cerai_dok` varchar(255) DEFAULT NULL,
    `blangko_akta_cerai` tinyint(1) DEFAULT '0',
    `diedit_oleh` varchar(30) DEFAULT NULL,
    `diedit_tanggal` datetime DEFAULT NULL,
    `diinput_oleh` varchar(30) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(30) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`perkara_id`),
    CONSTRAINT `perkara_akta_cerai_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1


CREATE TABLE `perkara_ikrar_talak` (
    `perkara_id` bigint(20) unsigned NOT NULL,
    `penetapan_majelis_hakim` date DEFAULT NULL,
    `majelis_hakim_id` varchar(50) DEFAULT NULL,
    `majelis_hakim_nama` varchar(500) DEFAULT NULL,
    `majelis_hakim_text` varchar(500) DEFAULT NULL,
    `penetapan_panitera_pengganti` date DEFAULT NULL,
    `panitera_pengganti_id` varchar(50) DEFAULT NULL,
    `panitera_pengganti_text` varchar(500) DEFAULT NULL,
    `penetapan_jurusita` date DEFAULT NULL,
    `jurusita_id` varchar(50) DEFAULT NULL,
    `jurusita_text` varchar(500) DEFAULT NULL,
    `sidang_id` bigint(20) DEFAULT NULL,
    `tanggal_penetapan_sidang_ikrar` date DEFAULT NULL,
    `tanggal_sidang_pertama` date DEFAULT NULL,
    `tgl_ikrar_talak` date DEFAULT NULL,
    `status_penetapan_ikrar_talak_id` char(1) DEFAULT NULL,
    `amar_ikrar_talak` longtext CHARACTER SET utf8mb4,
    `ikrar_talak_dok` varchar(255) DEFAULT NULL,
    `diinput_oleh` varchar(30) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(30) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`perkara_id`),
    CONSTRAINT `perkara_ikrar_talak_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `perkara_pihak1` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id(by system)',
    `urutan` int(11) unsigned DEFAULT NULL COMMENT 'Urutan: disi dengan bilangan',
    `pihak_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Pihak: merujuk ke tabel pihak kolom id',
    `jenis_pihak_id` tinyint(1) unsigned DEFAULT NULL COMMENT 'Id Jenis Pihak: merujuk ke tabel pihak kolom jenis_pihak_id(by system)',
    `nama` varchar(500) DEFAULT NULL COMMENT 'Nama: merujuk ke tabel pihak kolom nama(by system)',
    `alamat` varchar(500) DEFAULT NULL,
    `keterangan` varchar(255) DEFAULT NULL COMMENT 'Keterangan: Isian bebas',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaiki Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaiki Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `nama` (`nama`),
    KEY `perkara_id` (`perkara_id`),
    KEY `pihak_id` (`pihak_id`),
    CONSTRAINT `perkara_pihak1_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_pihak1_fk1` FOREIGN KEY (`pihak_id`) REFERENCES `pihak` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 13034 DEFAULT CHARSET = latin1 COMMENT = 'Data Pihak Pertama(Penggugat/Pemohon/Penuntut)'

CREATE TABLE `perkara_pihak2` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id(by system)',
    `urutan` int(11) unsigned DEFAULT NULL COMMENT 'Urutan: disii dengan bilangan',
    `pihak_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Pihak: merujuk ke tabel pihak',
    `jenis_pihak_id` tinyint(1) unsigned DEFAULT NULL COMMENT 'Id Jenis Pihak: merujuk ke tabel pihak kolom jenis_pihak_id(by system)',
    `nama` varchar(500) DEFAULT NULL COMMENT 'Nama: merujuk ke tabel pihak kolom nama(by system)',
    `alamat` varchar(500) DEFAULT NULL,
    `keterangan` varchar(255) DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `pangkat` varchar(100) DEFAULT NULL,
    `nrp` varchar(50) DEFAULT NULL,
    `jabatan` varchar(100) DEFAULT NULL,
    `kesatuan` varchar(100) DEFAULT NULL,
    `ditahan_oleh_id` int(11) unsigned DEFAULT NULL COMMENT 'Ditahan Oleh (terakhir): merujuk ke tabel penahan_terdakwa (by system)',
    `status_penahanan_id` tinyint(4) unsigned DEFAULT NULL COMMENT 'Status Penahanan (terakhir): merujuk ke tabel status_penahanan kolom id(by system)',
    `jenis_tahanan_id` tinyint(4) unsigned DEFAULT NULL COMMENT 'Jenis Tahanan (terakhir): merujuk ke tabel jenis_tahanan kolom id (by system)',
    `ghaib` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Apakah pihak tidak diketahui alamatnya? 1(ya), 0(tidak)',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput oleh(by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput tanggal(by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaiki oleh(by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaiki tanggal(by system)',
    PRIMARY KEY (`id`),
    KEY `nama` (`nama`),
    KEY `perkara_id` (`perkara_id`),
    KEY `pihak_id` (`pihak_id`),
    CONSTRAINT `perkara_pihak2_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_pihak2_fk1` FOREIGN KEY (`pihak_id`) REFERENCES `pihak` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 6343 DEFAULT CHARSET = latin1 COMMENT = 'Data Pihak Kedua(Tergugat/Termohon/Terdakwa)'

