
CREATE TABLE `perkara` (
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `jenis_acara` char(1) DEFAULT NULL,
    `alur_perkara_id` int(11) unsigned NOT NULL COMMENT 'Id Alur Perkara: merujuk ke tabel alur_perkara kolom id(by system)',
    `tanggal_pendaftaran` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran: isian tanggal',
    `jenis_perkara_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Jenis Perkara: merujuk ke tabel jenis_perkara kolom id',
    `jenis_perkara_kode` varchar(20) DEFAULT '' COMMENT 'Kode Jenis Perkara: merujuk ke tabel jenis_perkara kolom kode (by system)',
    `jenis_perkara_nama` varchar(100) DEFAULT '' COMMENT 'Nama Jenis Perkara: merujuk ke tabel jenis_perkara kolom nama (by system)',
    `jenis_perkara_text` varchar(400) DEFAULT '' COMMENT 'Nama Jenis Perkara lengkap dengan induk perkaranya(by system)',
    `nomor_urut_register` int(11) unsigned DEFAULT NULL COMMENT 'Nomor Urut Buku Register: Reset per bulan',
    `nomor_urut_perkara` int(11) unsigned DEFAULT NULL COMMENT 'Nomor Urut Perkara: reset per tahun untuk tiap alur_perkara_id (manual/by system)',
    `nomor_perkara` varchar(250) NOT NULL COMMENT 'Nomor Perkara: (manual/by system)',
    `nomor_indeks` varchar(250) DEFAULT NULL COMMENT 'Nomor Indeks Perkara: untuk keperluan pengurutan data berdasarkan tahun,alur perkara dan nomor urut perkara (by system)',
    `tanggal_surat` date DEFAULT NULL COMMENT 'Tanggal Surat Gugatan/Permohonan/Pelimpahan: isian tanggal',
    `nomor_surat` varchar(150) DEFAULT '' COMMENT 'Nomor Surat Gugatan/Permohonan/Pelimpahan: isian bebas',
    `surat_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Surat Gugatan/Permohonan/Pelimpahan: form upload',
    `pihak1_text` longtext COMMENT 'Penggugat/Pemohon/Penuntut: (by system)',
    `pengacara_pihak1` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak2_text` longtext COMMENT 'Tergugat/Termohon/Terdakwa: (by system)',
    `pengacara_pihak2` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak3_text` longtext COMMENT 'Pihak Ke Tiga yang melakukan Intervensi: (by system)',
    `pengacara_pihak3` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak4_text` longtext,
    `pengacara_pihak4` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `para_pihak` longtext,
    `pihak_dipublikasikan` char(1) DEFAULT 'Y' COMMENT 'Para Pihak Dipublikasikan: pilihan(Y=Ya; T=Tidak)',
    `posita` longtext CHARACTER SET utf8mb4,
    `petitum` longtext CHARACTER SET utf8mb4,
    `petitum_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Petitum: form upload',
    `nomor_dakwaan` varchar(150) DEFAULT NULL,
    `tanggal_dakwaan` date DEFAULT NULL,
    `dakwaan` longtext CHARACTER SET utf8mb4,
    `pasal_dakwaan` longtext,
    `dakwaan_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Dakwaan: form upload',
    `tanggal_rencana_perdamaian` date DEFAULT NULL COMMENT 'Tanggal Penerimaan Rencana Perdamaian: isian tanggal',
    `tanggal_pengesahan_perdamaian` date DEFAULT NULL COMMENT 'Tanggal Pengesahan Perdamaian: isian tanggal',
    `tanggal_penyelesaian_mediasi` date DEFAULT NULL COMMENT 'Tanggal Penyelesaian Mediasi: isian tanggal',
    `tanggal_penyelesaian_konsiliasi` date DEFAULT NULL COMMENT 'Tanggal Penyelesaian Konsiliasi: isian tanggal',
    `perkara_rujukan_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara Rujukan: merujuk ke tabel perkara kolom perkara_id',
    `nomor_perkara_rujukan` varchar(50) DEFAULT '' COMMENT 'Nomor Perkara yang menjadi rujukan: merujuk ke tabel perkara kolom nomor_perkara (by system)',
    `tanggal_pendaftaran_rujukan` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran Rujukan: merujuk ke tabel perkara kolom tanggal_pendaftaran (by system)',
    `catatan_pendaftaran` text COMMENT 'Catatan Pendaftaran: isian bebas',
    `prodeo` tinyint(1) DEFAULT '0' COMMENT 'Status Prodeo: 0=Tidak,1:Ya',
    `terdakwa_anak` tinyint(1) DEFAULT '0' COMMENT 'Terdakwa Anak-Anak: 0 Tidak 1=Ya',
    `tahapan_terakhir_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Tahapan Proses: merujuk ke tabel tahapan_proses kolom id (by system)',
    `tahapan_terakhir_text` varchar(50) DEFAULT '' COMMENT 'Nama Tahapan Terakhir: merujuk ke tabel tahapan_proses kolom nama (by system)',
    `proses_terakhir_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Proses Perkara Terakhir: menujuk ke tabel proses kolom id (by system)',
    `proses_terakhir_text` varchar(200) DEFAULT '' COMMENT 'Proses Perkara Terakhir: menujuk ke tabel proses kolom Nama(by system)',
    `nilai_sengketa` bigint(20) unsigned DEFAULT '0',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT '' COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT '' COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`perkara_id`),
    UNIQUE KEY `nomor_perkara` (`nomor_perkara`),
    KEY `jenis_perkara_id` (`jenis_perkara_id`),
    KEY `nomor_indeks` (`nomor_indeks`),
    KEY `alur_perkara_id` (`alur_perkara_id`),
    KEY `tanggal_pendaftaran` (`tanggal_pendaftaran`),
    KEY `tahapan_terakhir_id` (`tahapan_terakhir_id`),
    KEY `proses_terakhir_id` (`proses_terakhir_id`),
    KEY `diinput_tanggal` (`diinput_tanggal`),
    KEY `diperbaharui_tanggal` (`diperbaharui_tanggal`),
    CONSTRAINT `perkara_fk` FOREIGN KEY (`alur_perkara_id`) REFERENCES `alur_perkara` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Induk Perkara'


CREATE TABLE `perkara_pihak1` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id(by system)',
    `urutan` int(11) unsigned DEFAULT NULL COMMENT 'Urutan: disi dengan bilangan',
    `pihak_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Pihak: merujuk ke tabel pihak kolom id',
    `jenis_pihak_id` tinyint(1) unsigned DEFAULT NULL COMMENT 'Id Jenis Pihak: merujuk ke tabel pihak kolom jenis_pihak_id(by system)',
    `nama` varchar(500) DEFAULT NULL COMMENT 'Nama: merujuk ke tabel pihak kolom nama(by system)',
    `alamat` varchar(500) DEFAULT NULL,
    `keterangan` varchar(255) DEFAULT NULL COMMENT 'Keterangan: Isian bebas',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaiki Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaiki Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `nama` (`nama`),
    KEY `perkara_id` (`perkara_id`),
    KEY `pihak_id` (`pihak_id`),
    CONSTRAINT `perkara_pihak1_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_pihak1_fk1` FOREIGN KEY (`pihak_id`) REFERENCES `pihak` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 13283 DEFAULT CHARSET = latin1 COMMENT = 'Data Pihak Pertama(Penggugat/Pemohon/Penuntut)'

CREATE TABLE `pihak` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `jenis_pihak_id` tinyint(1) unsigned DEFAULT NULL COMMENT 'Jenis Pihak: merujuk ke tabel jenis_pihak kolom id',
    `jenis_indentitas` varchar(50) DEFAULT NULL COMMENT 'Jenis identitas: diisi dengan KTP/SIM/PASPOR',
    `nomor_indentitas` varchar(50) DEFAULT NULL COMMENT 'Nomor Identitas: isian bebas',
    `nama` varchar(500) DEFAULT NULL COMMENT 'Nama: isian bebas',
    `tempat_lahir` varchar(50) DEFAULT NULL COMMENT 'Tempat Lahir: isian bebas',
    `tanggal_lahir` date DEFAULT NULL COMMENT 'Tanggal lahir: selisih tanggal lahir dengan tanggal hari ini tidak boleh kurang dari 5 tahun',
    `jenis_kelamin` varchar(1) DEFAULT NULL COMMENT 'Jenis Kelamin: L= Laki-laki, P=Perempuan',
    `golongan_darah` varchar(2) DEFAULT NULL COMMENT 'Golongan darah: A/B/AB/O',
    `alamat` varchar(500) DEFAULT NULL COMMENT 'Alamat: Isian bebas',
    `rtrw` varchar(20) DEFAULT NULL COMMENT 'RT/RW: isian bebas',
    `kelurahan` varchar(50) DEFAULT NULL COMMENT 'Kelurahan/Desa: isian bebas',
    `kecamatan` varchar(50) DEFAULT NULL COMMENT 'Kecamatan: Isian bebas',
    `kabupaten_id` int(11) unsigned DEFAULT NULL COMMENT 'Kabupaten/Kota: merujuk ke tabel kabupaten kolom id',
    `kabupaten` varchar(50) DEFAULT NULL COMMENT 'Kabupaten/Kota: merujuk ke tabel kabupaten kolom nama(by system)',
    `propinsi_id` int(11) unsigned DEFAULT NULL COMMENT 'Propinsi: merujuk ke tabel propinsi kolom id',
    `propinsi` varchar(50) DEFAULT NULL COMMENT 'Propinsi: merujuk ke tabel propinsi kolom nama(by system)',
    `telepon` varchar(50) DEFAULT NULL COMMENT 'Nomor telepon: isian bebas',
    `fax` varchar(50) DEFAULT NULL COMMENT 'Nomor Fax: isian bebas',
    `email` varchar(50) DEFAULT NULL COMMENT 'Alamat email: isan format email',
    `agama_id` int(11) unsigned DEFAULT NULL COMMENT 'Agama: merujuk ke tabel agama kolom id',
    `agama_nama` varchar(50) DEFAULT NULL COMMENT 'Nama Agama: merujuk ke tabel agama kolom nama(by system)',
    `status_kawin` char(1) DEFAULT NULL COMMENT 'Statu Kawin: diisi dengan Kawin/Belum Kawin',
    `pekerjaan` varchar(255) DEFAULT NULL COMMENT 'Pekerjaan: isian bebas',
    `pendidikan_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Tingkat Pendidikan Terakhir: merujuk ke tabel tingkat_pendidikan kolom id',
    `pendidikan` varchar(50) DEFAULT NULL COMMENT 'Pendidikan terakhir: merujuk ke tabel pendidikan kolom kode',
    `warga_negara_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Negara: merujuk ke tabel negara kolom id',
    `warga_negara` varchar(50) DEFAULT NULL COMMENT 'Warga Negara: merujuk ke tabel negara kolom nama (by system)',
    `nama_ayah` varchar(50) DEFAULT NULL COMMENT 'Nama Ayah: isian bebas',
    `nama_ibu` varchar(50) DEFAULT NULL COMMENT 'Nama ibu: isian bebas',
    `keterangan` varchar(255) DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `foto` blob,
    `difabel` char(1) NOT NULL DEFAULT 'T' COMMENT 'Y=Ya, T = Tidak',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `nama` (`nama`),
    KEY `jenis_pihak_id` (`jenis_pihak_id`),
    KEY `kabupaten_id` (`kabupaten_id`),
    KEY `agama_id` (`agama_id`),
    KEY `warga_negara_id` (`warga_negara_id`),
    KEY `pendidikan_id` (`pendidikan_id`),
    CONSTRAINT `pihak_fk` FOREIGN KEY (`jenis_pihak_id`) REFERENCES `jenis_pihak` (`id`),
    CONSTRAINT `pihak_fk1` FOREIGN KEY (`kabupaten_id`) REFERENCES `kabupaten` (`id`),
    CONSTRAINT `pihak_fk2` FOREIGN KEY (`agama_id`) REFERENCES `agama` (`id`),
    CONSTRAINT `pihak_fk3` FOREIGN KEY (`warga_negara_id`) REFERENCES `negara` (`id`),
    CONSTRAINT `pihak_fk4` FOREIGN KEY (`pendidikan_id`) REFERENCES `tingkat_pendidikan` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 38027 DEFAULT CHARSET = latin1 AVG_ROW_LENGTH = 537 COMMENT = 'Data Para Pihak'

CREATE TABLE `perkara_putusan` (
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `tanggal_putusan` date NOT NULL,
    `putusan_verstek` varchar(1) DEFAULT NULL COMMENT 'Putusan Verstek: pilihan Y=Ya; T=Tidak',
    `sumber_hukum_id` varchar(20) DEFAULT NULL COMMENT 'Diputus Dengan: pilihan (KUH Perdata,KUH Dagang, Adat, UU/PP)',
    `status_putusan_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Status Putusan: merujuk ke tabel status_putusan kolom id',
    `status_putusan_kode` varchar(20) DEFAULT NULL COMMENT 'Kode Status Putusan: merujuk ke tabel status putusan kolom kode (by system)',
    `status_putusan_nama` varchar(100) DEFAULT NULL COMMENT 'Nama Status Putusan: merujuk ke tabel status_putusan kolom nama (by system)',
    `status_putusan_text` varchar(5000) DEFAULT '' COMMENT 'Keterangan Putusan: (by system)',
    `tanggal_cabut` date DEFAULT NULL COMMENT 'Tanggal Cabut, jika status putusan dicabut(status_putusan_id=7)',
    `tanggal_gugur` date DEFAULT NULL COMMENT 'Tanggal Gugur: jika status putusan gugur(status_putusan_id=6)',
    `amar_putusan` longtext CHARACTER SET utf8mb4,
    `amar_putusan_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen Amar Putusan: form upload',
    `amar_putusan_anonimisasi_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen Amar Putusan Anonimisasi: form upload',
    `penetapan_hakim_pengawas` date DEFAULT NULL COMMENT 'Tanggal Penetapan Hakim Pengawas: isian tanggal',
    `nomor_penetapan_hakim_pengawas` varchar(50) DEFAULT NULL COMMENT 'Nomor Penetapan Hakim Pengawas',
    `hakim_pengawas_id` varchar(50) DEFAULT NULL COMMENT 'Id Hakim Pengawas: dipisahkan dengan koma',
    `pengurus_id` varchar(50) DEFAULT NULL COMMENT 'Id Pengurus: dipisahkan dengan koma',
    `tanggal_penetapan_kreditur` date DEFAULT NULL COMMENT 'Tanggal Penetapan Panitia Kreditur: isian tanggal',
    `panitia_kreditur` varchar(500) DEFAULT NULL COMMENT 'Panitia Kreditur: isian bebas',
    `kurator_id` varchar(50) DEFAULT NULL COMMENT 'Id Kurator: dipisahkan dengan koma',
    `tanggal_berita_putusan` date DEFAULT NULL COMMENT 'Tanggal Pengumuman Dalam Berita Negara RI: isian tanggal',
    `nama_media_berita_putusan` varchar(250) DEFAULT NULL COMMENT 'Nama Media Berita: isian bebas',
    `tanggal_surat_kabar_putusan` date DEFAULT NULL COMMENT 'Tanggal Pengumuman Dalam Surat Kabar: isian tanggal',
    `nama_surat_kabar_putusan` varchar(250) DEFAULT NULL COMMENT 'Nama Surat Kabar: isian bebas',
    `tanggal_minutasi` date DEFAULT NULL COMMENT 'Tanggal Minutasi: isian tanggal',
    `pemberitahuan_putusan` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada para Pihak: isian tanggal',
    `pemberitahuan_putusan_pihak1` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada Pihak Penggugat/Pemohon/JPU: isian tanggal',
    `pemberitahuan_putusan_pihak2` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada Pihak Tergugat/Termohon/Terdakwa: isian tanggal',
    `pemberitahuan_putusan_pihak3` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada Pihak Intervensi: isian tanggal',
    `pemberitahuan_putusan_ankum` date DEFAULT NULL,
    `pemberitahuan_putusan_pepera` date DEFAULT NULL,
    `menerima_putusan_pihak1` date DEFAULT NULL COMMENT 'Tanggal JPU menerima putusan: isian tanggal',
    `menerima_putusan_pihak2` date DEFAULT NULL COMMENT 'Tanggal Terdakwa Menerima Putusan: isian tanggal',
    `penerbitan_salinan_putusan` date DEFAULT NULL COMMENT 'Tanggal Penerbitan Salinan Putusan',
    `kirim_salinan_putusan_pihak1` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada JPU: isian tanggal',
    `kirim_salinan_putusan_pihak2` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada Terdakwa: isian tanggal',
    `kirim_salinan_putusan_pihak3` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada Pihak Intervensi: isian tanggal',
    `kirim_salinan_putusan_penyidik` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada Penyidik: isian tanggal',
    `catatan_putusan` longtext CHARACTER SET utf8mb4,
    `nilai_ganti_kerugian` bigint(20) DEFAULT NULL,
    `tanggal_bht` date DEFAULT NULL,
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (
        `perkara_id`,
        `tanggal_putusan`
    ),
    KEY `tanggal_putusan` (`tanggal_putusan`),
    KEY `tanggal_cabut` (`tanggal_cabut`),
    KEY `tanggal_gugur` (`tanggal_gugur`),
    KEY `putusan_verstek` (`putusan_verstek`),
    KEY `status_putusan_id` (`status_putusan_id`),
    KEY `tanggal_minutasi` (`tanggal_minutasi`),
    CONSTRAINT `perkara_putusan_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Putusan Perkara'


CREATE TABLE `status_putusan` (
    `id` int(11) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `jenis_perkara_id` int(11) unsigned NOT NULL COMMENT 'Id Jenis Perkara: merujuk ke tabel jenis_perkara kolom id',
    `kode` varchar(20) DEFAULT NULL COMMENT 'Kode Status Putusan: isaian bebas',
    `nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Nama Status Putusan: isaian bebas',
    `keterangan` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Keterangan: isaian bebas',
    `aktif` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Status Aktif: pilihan Y=Ya; T=Tidak',
    `urutan` int(11) unsigned NOT NULL COMMENT 'Urutan berdasarkan jenis_proses_id',
    `satuan` tinyint(4) DEFAULT NULL COMMENT '1.Time/Hari,2.Nominal/Rupiah,3.checkbox,4.Uraian;',
    `jenis_pengadilan` tinyint(1) NOT NULL DEFAULT '1',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `perkara_id` (`jenis_perkara_id`),
    KEY `nama` (`nama`),
    KEY `kode` (`kode`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Referensi Status Putusan'

CREATE TABLE `perkara_jadwal_sidang` (
    `id` bigint(20) unsigned NOT NULL COMMENT 'Primary key: (by system)',
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id',
    `verzet` char(1) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT 'T' COMMENT 'flag untuk sidang verzet/biasa (by system)',
    `keberatan` char(1) DEFAULT 'T' COMMENT 'flag untuk sidang perkara keberatan',
    `ikrar_talak` char(1) DEFAULT 'T',
    `urutan` int(11) unsigned NOT NULL DEFAULT '1' COMMENT 'Urutan Jadwal Sidang Salam Satu Hari yang sama: (by system)',
    `tanggal_sidang` date NOT NULL COMMENT 'Tanggal Sidang: isian tanggal',
    `jam_sidang` time DEFAULT NULL COMMENT 'Mulai Jam Sidang: isian format jam:menit',
    `sampai_jam` time DEFAULT NULL COMMENT 'Sampai Jam Sidang : isian format jam:menit',
    `agenda_id` varchar(50) DEFAULT NULL COMMENT 'Agenda Sidang : merujuk ke tabel agenda_sidang dengan pemisah koma',
    `agenda` varchar(500) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Agenda Sidang: isian bebas',
    `ruangan_id` int(11) unsigned DEFAULT NULL COMMENT 'id Ruangan Sidang: merujuk ke tabel ruangan_sidang kolom id',
    `ruangan` varchar(50) DEFAULT NULL COMMENT 'Ruangan Sidang: merujuk ke tabel ruangan_sidang kolom nama (by system)',
    `sidang_keliling` char(1) DEFAULT 'T' COMMENT 'Y dan T',
    `dihadiri_oleh` tinyint(3) DEFAULT NULL,
    `ditunda` char(1) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT 'T' COMMENT 'Sidang Ditunda: pilihan Y=Ya; T=Tidak',
    `alasan_ditunda` varchar(500) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Alasan Ditunda: isian bebas',
    `sidang_ditempat` tinyint(1) DEFAULT '0' COMMENT 'Sidang Di Tempat: 0=Tidak, 1=Ya',
    `sifat_sidang` char(1) DEFAULT 'Y' COMMENT 'Y: Dibuka Untuk Umum, T: Tertutup Untuk Umum',
    `keterangan` varchar(500) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `edoc_bas` varchar(250) DEFAULT NULL,
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `verzet` (`verzet`),
    KEY `perkara_id` (`perkara_id`),
    KEY `ruangan_id` (`ruangan_id`),
    KEY `tanggal_sidang` (`tanggal_sidang`),
    KEY `jam_sidang` (`jam_sidang`),
    CONSTRAINT `perkara_jadwal_sidang_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_jadwal_sidang_fk1` FOREIGN KEY (`ruangan_id`) REFERENCES `ruangan_sidang` (`id`) ON DELETE SET NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Jadwal Pesidangan'


CREATE TABLE `perkara_data_pernikahan` (
    `perkara_id` bigint(20) unsigned NOT NULL,
    `tgl_nikah` date NOT NULL,
    `tgl_kutipan_akta_nikah` date NOT NULL,
    `no_kutipan_akta_nikah` varchar(100) DEFAULT NULL,
    `kua_tempat_nikah` varchar(255) DEFAULT NULL,
    `kode_kua` int(11) DEFAULT NULL COMMENT 'merujuk kode_kua ref_kua',
    `diedit_oleh` varchar(30) DEFAULT NULL,
    `diedit_tanggal` datetime DEFAULT NULL,
    `diinput_oleh` varchar(30) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(30) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`perkara_id`),
    CONSTRAINT `perkara_data_pernikahan_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1


CREATE TABLE `perkara_alasan_nikah` (
    `perkara_id` bigint(20) NOT NULL,
    `jenis_perkara_id` int(4) NOT NULL,
    `jenis_alasan_id` int(2) NOT NULL,
    `alasan_id` int(2) NOT NULL,
    `nama` varchar(255) DEFAULT NULL,
    `nominal_penghasilan` decimal(20, 0) DEFAULT NULL COMMENT 'khusus poligami',
    `diinput_oleh` varchar(255) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(255) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`perkara_id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1


CREATE TABLE `perkara_mempelai_dk` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key: (by system)',
    `perkara_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id(by system)',
    `nama` varchar(255) DEFAULT NULL,
    `nik` varchar(50) DEFAULT NULL,
    `tempat_lahir` varchar(255) DEFAULT NULL,
    `tanggal_lahir` date DEFAULT NULL,
    `pendidikan` tinyint(1) DEFAULT NULL COMMENT 'merujuk ke ID tabel referensi_tingkat_pendidikan',
    `jenis_mempelai` char(1) DEFAULT NULL COMMENT '1 mempelai laki-laki, 2 mempelai wanita',
    `pekerjaan` varchar(255) DEFAULT NULL COMMENT 'merujuk ke ID tabel referensi_pekerjaan',
    `nominal_penghasilan` decimal(20, 0) unsigned DEFAULT NULL,
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaiki Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaiki Tanggal: (by system)',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1385 DEFAULT CHARSET = latin1


CREATE TABLE `perkara_ikrar_talak` (
    `perkara_id` bigint(20) unsigned NOT NULL,
    `penetapan_majelis_hakim` date DEFAULT NULL,
    `majelis_hakim_id` varchar(50) DEFAULT NULL,
    `majelis_hakim_nama` varchar(500) DEFAULT NULL,
    `majelis_hakim_text` varchar(500) DEFAULT NULL,
    `penetapan_panitera_pengganti` date DEFAULT NULL,
    `panitera_pengganti_id` varchar(50) DEFAULT NULL,
    `panitera_pengganti_text` varchar(500) DEFAULT NULL,
    `penetapan_jurusita` date DEFAULT NULL,
    `jurusita_id` varchar(50) DEFAULT NULL,
    `jurusita_text` varchar(500) DEFAULT NULL,
    `sidang_id` bigint(20) DEFAULT NULL,
    `tanggal_penetapan_sidang_ikrar` date DEFAULT NULL,
    `tanggal_sidang_pertama` date DEFAULT NULL,
    `tgl_ikrar_talak` date DEFAULT NULL,
    `status_penetapan_ikrar_talak_id` char(1) DEFAULT NULL,
    `amar_ikrar_talak` longtext CHARACTER SET utf8mb4,
    `ikrar_talak_dok` varchar(255) DEFAULT NULL,
    `diinput_oleh` varchar(30) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(30) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`perkara_id`),
    CONSTRAINT `perkara_ikrar_talak_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `perkara_akta_cerai` (
    `perkara_id` bigint(20) unsigned NOT NULL,
    `tahun_akta_cerai` int(11) DEFAULT NULL,
    `nomor_urut_akta_cerai` int(11) DEFAULT NULL,
    `nomor_akta_cerai` varchar(50) DEFAULT NULL,
    `tgl_akta_cerai` date DEFAULT NULL,
    `no_seri_akta_cerai` varchar(50) DEFAULT NULL,
    `jenis_cerai` varchar(50) DEFAULT NULL,
    `faktor_perceraian_id` int(11) DEFAULT NULL,
    `qobla_bada` tinyint(4) DEFAULT NULL,
    `perceraian_ke` int(11) DEFAULT NULL,
    `keadaan_istri` tinyint(4) DEFAULT NULL,
    `tgl_penyerahan_akta_cerai` date DEFAULT NULL,
    `tgl_penyerahan_akta_cerai_pihak2` date DEFAULT NULL,
    `akta_cerai_dok` varchar(255) DEFAULT NULL,
    `blangko_akta_cerai` tinyint(1) DEFAULT '0',
    `diedit_oleh` varchar(30) DEFAULT NULL,
    `diedit_tanggal` datetime DEFAULT NULL,
    `diinput_oleh` varchar(30) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(30) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`perkara_id`),
    CONSTRAINT `perkara_akta_cerai_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1


CREATE TABLE `perkara_pihak2` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id(by system)',
    `urutan` int(11) unsigned DEFAULT NULL COMMENT 'Urutan: disii dengan bilangan',
    `pihak_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Pihak: merujuk ke tabel pihak',
    `jenis_pihak_id` tinyint(1) unsigned DEFAULT NULL COMMENT 'Id Jenis Pihak: merujuk ke tabel pihak kolom jenis_pihak_id(by system)',
    `nama` varchar(500) DEFAULT NULL COMMENT 'Nama: merujuk ke tabel pihak kolom nama(by system)',
    `alamat` varchar(500) DEFAULT NULL,
    `keterangan` varchar(255) DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `pangkat` varchar(100) DEFAULT NULL,
    `nrp` varchar(50) DEFAULT NULL,
    `jabatan` varchar(100) DEFAULT NULL,
    `kesatuan` varchar(100) DEFAULT NULL,
    `ditahan_oleh_id` int(11) unsigned DEFAULT NULL COMMENT 'Ditahan Oleh (terakhir): merujuk ke tabel penahan_terdakwa (by system)',
    `status_penahanan_id` tinyint(4) unsigned DEFAULT NULL COMMENT 'Status Penahanan (terakhir): merujuk ke tabel status_penahanan kolom id(by system)',
    `jenis_tahanan_id` tinyint(4) unsigned DEFAULT NULL COMMENT 'Jenis Tahanan (terakhir): merujuk ke tabel jenis_tahanan kolom id (by system)',
    `ghaib` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Apakah pihak tidak diketahui alamatnya? 1(ya), 0(tidak)',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput oleh(by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput tanggal(by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaiki oleh(by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaiki tanggal(by system)',
    PRIMARY KEY (`id`),
    KEY `nama` (`nama`),
    KEY `perkara_id` (`perkara_id`),
    KEY `pihak_id` (`pihak_id`),
    CONSTRAINT `perkara_pihak2_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_pihak2_fk1` FOREIGN KEY (`pihak_id`) REFERENCES `pihak` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 6463 DEFAULT CHARSET = latin1 COMMENT = 'Data Pihak Kedua(Tergugat/Termohon/Terdakwa)'




