CREATE TABLE `perkara` (
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `jenis_acara` char(1) DEFAULT NULL,
    `alur_perkara_id` int(11) unsigned NOT NULL COMMENT 'Id Alur Perkara: merujuk ke tabel alur_perkara kolom id(by system)',
    `tanggal_pendaftaran` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran: isian tanggal',
    `jenis_perkara_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Jenis Perkara: merujuk ke tabel jenis_perkara kolom id',
    `jenis_perkara_kode` varchar(20) DEFAULT '' COMMENT 'Kode Jenis Perkara: merujuk ke tabel jenis_perkara kolom kode (by system)',
    `jenis_perkara_nama` varchar(100) DEFAULT '' COMMENT 'Nama Jenis Perkara: merujuk ke tabel jenis_perkara kolom nama (by system)',
    `jenis_perkara_text` varchar(400) DEFAULT '' COMMENT 'Nama Jenis Perkara lengkap dengan induk perkaranya(by system)',
    `nomor_urut_register` int(11) unsigned DEFAULT NULL COMMENT 'Nomor Urut Buku Register: Reset per bulan',
    `nomor_urut_perkara` int(11) unsigned DEFAULT NULL COMMENT 'Nomor Urut Perkara: reset per tahun untuk tiap alur_perkara_id (manual/by system)',
    `nomor_perkara` varchar(250) NOT NULL COMMENT 'Nomor Perkara: (manual/by system)',
    `nomor_indeks` varchar(250) DEFAULT NULL COMMENT 'Nomor Indeks Perkara: untuk keperluan pengurutan data berdasarkan tahun,alur perkara dan nomor urut perkara (by system)',
    `tanggal_surat` date DEFAULT NULL COMMENT 'Tanggal Surat Gugatan/Permohonan/Pelimpahan: isian tanggal',
    `nomor_surat` varchar(150) DEFAULT '' COMMENT 'Nomor Surat Gugatan/Permohonan/Pelimpahan: isian bebas',
    `surat_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Surat Gugatan/Permohonan/Pelimpahan: form upload',
    `pihak1_text` longtext COMMENT 'Penggugat/Pemohon/Penuntut: (by system)',
    `pengacara_pihak1` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak2_text` longtext COMMENT 'Tergugat/Termohon/Terdakwa: (by system)',
    `pengacara_pihak2` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak3_text` longtext COMMENT 'Pihak Ke Tiga yang melakukan Intervensi: (by system)',
    `pengacara_pihak3` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak4_text` longtext,
    `pengacara_pihak4` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `para_pihak` longtext,
    `pihak_dipublikasikan` char(1) DEFAULT 'Y' COMMENT 'Para Pihak Dipublikasikan: pilihan(Y=Ya; T=Tidak)',
    `posita` longtext CHARACTER SET utf8mb4,
    `petitum` longtext CHARACTER SET utf8mb4,
    `petitum_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Petitum: form upload',
    `nomor_dakwaan` varchar(150) DEFAULT NULL,
    `tanggal_dakwaan` date DEFAULT NULL,
    `dakwaan` longtext CHARACTER SET utf8mb4,
    `pasal_dakwaan` longtext,
    `dakwaan_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Dakwaan: form upload',
    `tanggal_rencana_perdamaian` date DEFAULT NULL COMMENT 'Tanggal Penerimaan Rencana Perdamaian: isian tanggal',
    `tanggal_pengesahan_perdamaian` date DEFAULT NULL COMMENT 'Tanggal Pengesahan Perdamaian: isian tanggal',
    `tanggal_penyelesaian_mediasi` date DEFAULT NULL COMMENT 'Tanggal Penyelesaian Mediasi: isian tanggal',
    `tanggal_penyelesaian_konsiliasi` date DEFAULT NULL COMMENT 'Tanggal Penyelesaian Konsiliasi: isian tanggal',
    `perkara_rujukan_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara Rujukan: merujuk ke tabel perkara kolom perkara_id',
    `nomor_perkara_rujukan` varchar(50) DEFAULT '' COMMENT 'Nomor Perkara yang menjadi rujukan: merujuk ke tabel perkara kolom nomor_perkara (by system)',
    `tanggal_pendaftaran_rujukan` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran Rujukan: merujuk ke tabel perkara kolom tanggal_pendaftaran (by system)',
    `catatan_pendaftaran` text COMMENT 'Catatan Pendaftaran: isian bebas',
    `prodeo` tinyint(1) DEFAULT '0' COMMENT 'Status Prodeo: 0=Tidak,1:Ya',
    `terdakwa_anak` tinyint(1) DEFAULT '0' COMMENT 'Terdakwa Anak-Anak: 0 Tidak 1=Ya',
    `tahapan_terakhir_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Tahapan Proses: merujuk ke tabel tahapan_proses kolom id (by system)',
    `tahapan_terakhir_text` varchar(50) DEFAULT '' COMMENT 'Nama Tahapan Terakhir: merujuk ke tabel tahapan_proses kolom nama (by system)',
    `proses_terakhir_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Proses Perkara Terakhir: menujuk ke tabel proses kolom id (by system)',
    `proses_terakhir_text` varchar(200) DEFAULT '' COMMENT 'Proses Perkara Terakhir: menujuk ke tabel proses kolom Nama(by system)',
    `nilai_sengketa` bigint(20) unsigned DEFAULT '0',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT '' COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT '' COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`perkara_id`),
    UNIQUE KEY `nomor_perkara` (`nomor_perkara`),
    KEY `jenis_perkara_id` (`jenis_perkara_id`),
    KEY `nomor_indeks` (`nomor_indeks`),
    KEY `alur_perkara_id` (`alur_perkara_id`),
    KEY `tanggal_pendaftaran` (`tanggal_pendaftaran`),
    KEY `tahapan_terakhir_id` (`tahapan_terakhir_id`),
    KEY `proses_terakhir_id` (`proses_terakhir_id`),
    KEY `diinput_tanggal` (`diinput_tanggal`),
    KEY `diperbaharui_tanggal` (`diperbaharui_tanggal`),
    CONSTRAINT `perkara_fk` FOREIGN KEY (`alur_perkara_id`) REFERENCES `alur_perkara` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Induk Perkara'

CREATE TABLE `dirput_dokumen` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) NOT NULL,
    `dokumen_ref_id` bigint(20) NOT NULL,
    `filename` varchar(255) NOT NULL,
    `path_filename` varchar(355) NOT NULL,
    `created_by` varchar(255) NOT NULL,
    `created_date` date NOT NULL,
    `updated_by` varchar(255) DEFAULT NULL,
    `updated_date` date DEFAULT NULL,
    `pihak_detil_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'merujuk ke tabel banding_detil, kasasi_detil, pk_detil pada kolom id',
    `keterangan` varchar(255) DEFAULT NULL,
    `flag_sync` tinyint(1) DEFAULT NULL COMMENT 'penanda antrian sudah terupload atau belum',
    `pengajuan_id` tinyint(1) unsigned NOT NULL COMMENT '1 = tidak diajukan, 2 = banding, 3 = kasasi, 4 = pk, 5 = grasi',
    `published` tinyint(1) DEFAULT '0' COMMENT '0 = tidak dipublished, 1 = di published',
    `link_dirput` varchar(255) DEFAULT NULL,
    PRIMARY KEY (
        `perkara_id`,
        `dokumen_ref_id`,
        `pihak_detil_id`,
        `pengajuan_id`
    ),
    KEY `id` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 22971 DEFAULT CHARSET = latin1 COMMENT = 'Dokumen Dirput'

CREATE TABLE `perkara_putusan` (
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `tanggal_putusan` date NOT NULL,
    `putusan_verstek` varchar(1) DEFAULT NULL COMMENT 'Putusan Verstek: pilihan Y=Ya; T=Tidak',
    `sumber_hukum_id` varchar(20) DEFAULT NULL COMMENT 'Diputus Dengan: pilihan (KUH Perdata,KUH Dagang, Adat, UU/PP)',
    `status_putusan_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Status Putusan: merujuk ke tabel status_putusan kolom id',
    `status_putusan_kode` varchar(20) DEFAULT NULL COMMENT 'Kode Status Putusan: merujuk ke tabel status putusan kolom kode (by system)',
    `status_putusan_nama` varchar(100) DEFAULT NULL COMMENT 'Nama Status Putusan: merujuk ke tabel status_putusan kolom nama (by system)',
    `status_putusan_text` varchar(5000) DEFAULT '' COMMENT 'Keterangan Putusan: (by system)',
    `tanggal_cabut` date DEFAULT NULL COMMENT 'Tanggal Cabut, jika status putusan dicabut(status_putusan_id=7)',
    `tanggal_gugur` date DEFAULT NULL COMMENT 'Tanggal Gugur: jika status putusan gugur(status_putusan_id=6)',
    `amar_putusan` longtext CHARACTER SET utf8mb4,
    `amar_putusan_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen Amar Putusan: form upload',
    `amar_putusan_anonimisasi_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen Amar Putusan Anonimisasi: form upload',
    `penetapan_hakim_pengawas` date DEFAULT NULL COMMENT 'Tanggal Penetapan Hakim Pengawas: isian tanggal',
    `nomor_penetapan_hakim_pengawas` varchar(50) DEFAULT NULL COMMENT 'Nomor Penetapan Hakim Pengawas',
    `hakim_pengawas_id` varchar(50) DEFAULT NULL COMMENT 'Id Hakim Pengawas: dipisahkan dengan koma',
    `pengurus_id` varchar(50) DEFAULT NULL COMMENT 'Id Pengurus: dipisahkan dengan koma',
    `tanggal_penetapan_kreditur` date DEFAULT NULL COMMENT 'Tanggal Penetapan Panitia Kreditur: isian tanggal',
    `panitia_kreditur` varchar(500) DEFAULT NULL COMMENT 'Panitia Kreditur: isian bebas',
    `kurator_id` varchar(50) DEFAULT NULL COMMENT 'Id Kurator: dipisahkan dengan koma',
    `tanggal_berita_putusan` date DEFAULT NULL COMMENT 'Tanggal Pengumuman Dalam Berita Negara RI: isian tanggal',
    `nama_media_berita_putusan` varchar(250) DEFAULT NULL COMMENT 'Nama Media Berita: isian bebas',
    `tanggal_surat_kabar_putusan` date DEFAULT NULL COMMENT 'Tanggal Pengumuman Dalam Surat Kabar: isian tanggal',
    `nama_surat_kabar_putusan` varchar(250) DEFAULT NULL COMMENT 'Nama Surat Kabar: isian bebas',
    `tanggal_minutasi` date DEFAULT NULL COMMENT 'Tanggal Minutasi: isian tanggal',
    `pemberitahuan_putusan` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada para Pihak: isian tanggal',
    `pemberitahuan_putusan_pihak1` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada Pihak Penggugat/Pemohon/JPU: isian tanggal',
    `pemberitahuan_putusan_pihak2` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada Pihak Tergugat/Termohon/Terdakwa: isian tanggal',
    `pemberitahuan_putusan_pihak3` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada Pihak Intervensi: isian tanggal',
    `pemberitahuan_putusan_ankum` date DEFAULT NULL,
    `pemberitahuan_putusan_pepera` date DEFAULT NULL,
    `menerima_putusan_pihak1` date DEFAULT NULL COMMENT 'Tanggal JPU menerima putusan: isian tanggal',
    `menerima_putusan_pihak2` date DEFAULT NULL COMMENT 'Tanggal Terdakwa Menerima Putusan: isian tanggal',
    `penerbitan_salinan_putusan` date DEFAULT NULL COMMENT 'Tanggal Penerbitan Salinan Putusan',
    `kirim_salinan_putusan_pihak1` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada JPU: isian tanggal',
    `kirim_salinan_putusan_pihak2` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada Terdakwa: isian tanggal',
    `kirim_salinan_putusan_pihak3` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada Pihak Intervensi: isian tanggal',
    `kirim_salinan_putusan_penyidik` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada Penyidik: isian tanggal',
    `catatan_putusan` longtext CHARACTER SET utf8mb4,
    `nilai_ganti_kerugian` bigint(20) DEFAULT NULL,
    `tanggal_bht` date DEFAULT NULL,
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (
        `perkara_id`,
        `tanggal_putusan`
    ),
    KEY `tanggal_putusan` (`tanggal_putusan`),
    KEY `tanggal_cabut` (`tanggal_cabut`),
    KEY `tanggal_gugur` (`tanggal_gugur`),
    KEY `putusan_verstek` (`putusan_verstek`),
    KEY `status_putusan_id` (`status_putusan_id`),
    KEY `tanggal_minutasi` (`tanggal_minutasi`),
    CONSTRAINT `perkara_putusan_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Putusan Perkara'