CREATE TABLE `perkara` (
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `jenis_acara` char(1) DEFAULT NULL,
    `alur_perkara_id` int(11) unsigned NOT NULL COMMENT 'Id Alur Perkara: merujuk ke tabel alur_perkara kolom id(by system)',
    `tanggal_pendaftaran` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran: isian tanggal',
    `jenis_perkara_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Jenis Perkara: merujuk ke tabel jenis_perkara kolom id',
    `jenis_perkara_kode` varchar(20) DEFAULT '' COMMENT 'Kode Jenis Perkara: merujuk ke tabel jenis_perkara kolom kode (by system)',
    `jenis_perkara_nama` varchar(100) DEFAULT '' COMMENT 'Nama Jenis Perkara: merujuk ke tabel jenis_perkara kolom nama (by system)',
    `jenis_perkara_text` varchar(400) DEFAULT '' COMMENT 'Nama Jenis Perkara lengkap dengan induk perkaranya(by system)',
    `nomor_urut_register` int(11) unsigned DEFAULT NULL COMMENT 'Nomor Urut Buku Register: Reset per bulan',
    `nomor_urut_perkara` int(11) unsigned DEFAULT NULL COMMENT 'Nomor Urut Perkara: reset per tahun untuk tiap alur_perkara_id (manual/by system)',
    `nomor_perkara` varchar(250) NOT NULL COMMENT 'Nomor Perkara: (manual/by system)',
    `nomor_indeks` varchar(250) DEFAULT NULL COMMENT 'Nomor Indeks Perkara: untuk keperluan pengurutan data berdasarkan tahun,alur perkara dan nomor urut perkara (by system)',
    `tanggal_surat` date DEFAULT NULL COMMENT 'Tanggal Surat Gugatan/Permohonan/Pelimpahan: isian tanggal',
    `nomor_surat` varchar(150) DEFAULT '' COMMENT 'Nomor Surat Gugatan/Permohonan/Pelimpahan: isian bebas',
    `surat_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Surat Gugatan/Permohonan/Pelimpahan: form upload',
    `pihak1_text` longtext COMMENT 'Penggugat/Pemohon/Penuntut: (by system)',
    `pengacara_pihak1` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak2_text` longtext COMMENT 'Tergugat/Termohon/Terdakwa: (by system)',
    `pengacara_pihak2` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak3_text` longtext COMMENT 'Pihak Ke Tiga yang melakukan Intervensi: (by system)',
    `pengacara_pihak3` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak4_text` longtext,
    `pengacara_pihak4` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `para_pihak` longtext,
    `pihak_dipublikasikan` char(1) DEFAULT 'Y' COMMENT 'Para Pihak Dipublikasikan: pilihan(Y=Ya; T=Tidak)',
    `posita` longtext CHARACTER SET utf8mb4,
    `petitum` longtext CHARACTER SET utf8mb4,
    `petitum_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Petitum: form upload',
    `nomor_dakwaan` varchar(150) DEFAULT NULL,
    `tanggal_dakwaan` date DEFAULT NULL,
    `dakwaan` longtext CHARACTER SET utf8mb4,
    `pasal_dakwaan` longtext,
    `dakwaan_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Dakwaan: form upload',
    `tanggal_rencana_perdamaian` date DEFAULT NULL COMMENT 'Tanggal Penerimaan Rencana Perdamaian: isian tanggal',
    `tanggal_pengesahan_perdamaian` date DEFAULT NULL COMMENT 'Tanggal Pengesahan Perdamaian: isian tanggal',
    `tanggal_penyelesaian_mediasi` date DEFAULT NULL COMMENT 'Tanggal Penyelesaian Mediasi: isian tanggal',
    `tanggal_penyelesaian_konsiliasi` date DEFAULT NULL COMMENT 'Tanggal Penyelesaian Konsiliasi: isian tanggal',
    `perkara_rujukan_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara Rujukan: merujuk ke tabel perkara kolom perkara_id',
    `nomor_perkara_rujukan` varchar(50) DEFAULT '' COMMENT 'Nomor Perkara yang menjadi rujukan: merujuk ke tabel perkara kolom nomor_perkara (by system)',
    `tanggal_pendaftaran_rujukan` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran Rujukan: merujuk ke tabel perkara kolom tanggal_pendaftaran (by system)',
    `catatan_pendaftaran` text COMMENT 'Catatan Pendaftaran: isian bebas',
    `prodeo` tinyint(1) DEFAULT '0' COMMENT 'Status Prodeo: 0=Tidak,1:Ya',
    `terdakwa_anak` tinyint(1) DEFAULT '0' COMMENT 'Terdakwa Anak-Anak: 0 Tidak 1=Ya',
    `tahapan_terakhir_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Tahapan Proses: merujuk ke tabel tahapan_proses kolom id (by system)',
    `tahapan_terakhir_text` varchar(50) DEFAULT '' COMMENT 'Nama Tahapan Terakhir: merujuk ke tabel tahapan_proses kolom nama (by system)',
    `proses_terakhir_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Proses Perkara Terakhir: menujuk ke tabel proses kolom id (by system)',
    `proses_terakhir_text` varchar(200) DEFAULT '' COMMENT 'Proses Perkara Terakhir: menujuk ke tabel proses kolom Nama(by system)',
    `nilai_sengketa` bigint(20) unsigned DEFAULT '0',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT '' COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT '' COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`perkara_id`),
    UNIQUE KEY `nomor_perkara` (`nomor_perkara`),
    KEY `jenis_perkara_id` (`jenis_perkara_id`),
    KEY `nomor_indeks` (`nomor_indeks`),
    KEY `alur_perkara_id` (`alur_perkara_id`),
    KEY `tanggal_pendaftaran` (`tanggal_pendaftaran`),
    KEY `tahapan_terakhir_id` (`tahapan_terakhir_id`),
    KEY `proses_terakhir_id` (`proses_terakhir_id`),
    KEY `diinput_tanggal` (`diinput_tanggal`),
    KEY `diperbaharui_tanggal` (`diperbaharui_tanggal`),
    CONSTRAINT `perkara_fk` FOREIGN KEY (`alur_perkara_id`) REFERENCES `alur_perkara` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Induk Perkara'

CREATE TABLE `perkara_efiling_id` (
    `perkara_id` bigint(20) unsigned NOT NULL,
    `efiling_id` bigint(20) NOT NULL,
    PRIMARY KEY (`efiling_id`),
    KEY `perkara_id` (`perkara_id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `perkara_efiling` (
    `efiling_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `satker_id` int(11) NOT NULL COMMENT 'pengadilan id tempat pendaftaran',
    `juncto_efiling_id` bigint(20) unsigned DEFAULT NULL,
    `kode_satker` varchar(10) DEFAULT NULL COMMENT 'kode satker',
    `nama_satker` varchar(255) DEFAULT NULL COMMENT 'nama pengadilan',
    `user_id` bigint(20) DEFAULT NULL COMMENT 'ID User Kepemilikan',
    `nomor_register` varchar(30) DEFAULT NULL COMMENT 'Nomor Register Pendaftaran Online',
    `tanggal_pendaftaran` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran: isian tanggal',
    `alur_perkara_id` int(11) unsigned NOT NULL DEFAULT '1' COMMENT 'Id Alur Perkara: merujuk ke tabel alur_perkara kolom id(by system)',
    `jenis_perkara_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Jenis Perkara: merujuk ke tabel jenis_perkara kolom id',
    `jenis_perkara_nama` varchar(100) DEFAULT '' COMMENT 'Nama Jenis Perkara: merujuk ke tabel jenis_perkara kolom nama (by system)',
    `status_pendaftaran_id` int(11) DEFAULT NULL COMMENT 'Merujuk ke ref_status_pendaftaran',
    `status_pendaftaran_text` varchar(255) DEFAULT NULL COMMENT 'Merujuk ke ref_status',
    `nomor_va` char(100) DEFAULT NULL,
    `digit_ran` double DEFAULT NULL COMMENT 'Angka Acak yang ditambahkan',
    `jumlah_skum` double DEFAULT NULL COMMENT 'Nominal Pembayaran',
    `tanggal_bayar` datetime DEFAULT NULL,
    `batas_pembayaran` datetime DEFAULT NULL COMMENT 'Batas Pembayaran',
    `status_pembayaran` char(1) DEFAULT '0' COMMENT '1: Dibayar else: Blm Dibayar',
    `nomor_perkara` varchar(250) DEFAULT NULL COMMENT 'Nomor Perkara setelah di setujui',
    `tgl_pendaftaran_perkara` date DEFAULT NULL,
    `diinput_oleh` varchar(30) DEFAULT '' COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT '' COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    `status_litigasi` tinyint(1) DEFAULT NULL,
    `informasi_tambahan` longtext CHARACTER SET utf8mb4,
    PRIMARY KEY (`efiling_id`, `satker_id`),
    KEY `jenis_perkara_id` (`jenis_perkara_id`),
    KEY `alur_perkara_id` (`alur_perkara_id`),
    KEY `tanggal_pendaftaran` (`tanggal_pendaftaran`),
    KEY `diinput_tanggal` (`diinput_tanggal`),
    KEY `diperbaharui_tanggal` (`diperbaharui_tanggal`),
    KEY `nomor_perkara` (`nomor_perkara`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Induk Perkara'

CREATE TABLE `perkara_pihak1` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id(by system)',
    `urutan` int(11) unsigned DEFAULT NULL COMMENT 'Urutan: disi dengan bilangan',
    `pihak_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Pihak: merujuk ke tabel pihak kolom id',
    `jenis_pihak_id` tinyint(1) unsigned DEFAULT NULL COMMENT 'Id Jenis Pihak: merujuk ke tabel pihak kolom jenis_pihak_id(by system)',
    `nama` varchar(500) DEFAULT NULL COMMENT 'Nama: merujuk ke tabel pihak kolom nama(by system)',
    `alamat` varchar(500) DEFAULT NULL,
    `keterangan` varchar(255) DEFAULT NULL COMMENT 'Keterangan: Isian bebas',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaiki Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaiki Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `nama` (`nama`),
    KEY `perkara_id` (`perkara_id`),
    KEY `pihak_id` (`pihak_id`),
    CONSTRAINT `perkara_pihak1_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_pihak1_fk1` FOREIGN KEY (`pihak_id`) REFERENCES `pihak` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 13034 DEFAULT CHARSET = latin1 COMMENT = 'Data Pihak Pertama(Penggugat/Pemohon/Penuntut)'

CREATE TABLE `pihak` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `jenis_pihak_id` tinyint(1) unsigned DEFAULT NULL COMMENT 'Jenis Pihak: merujuk ke tabel jenis_pihak kolom id',
    `jenis_indentitas` varchar(50) DEFAULT NULL COMMENT 'Jenis identitas: diisi dengan KTP/SIM/PASPOR',
    `nomor_indentitas` varchar(50) DEFAULT NULL COMMENT 'Nomor Identitas: isian bebas',
    `nama` varchar(500) DEFAULT NULL COMMENT 'Nama: isian bebas',
    `tempat_lahir` varchar(50) DEFAULT NULL COMMENT 'Tempat Lahir: isian bebas',
    `tanggal_lahir` date DEFAULT NULL COMMENT 'Tanggal lahir: selisih tanggal lahir dengan tanggal hari ini tidak boleh kurang dari 5 tahun',
    `jenis_kelamin` varchar(1) DEFAULT NULL COMMENT 'Jenis Kelamin: L= Laki-laki, P=Perempuan',
    `golongan_darah` varchar(2) DEFAULT NULL COMMENT 'Golongan darah: A/B/AB/O',
    `alamat` varchar(500) DEFAULT NULL COMMENT 'Alamat: Isian bebas',
    `rtrw` varchar(20) DEFAULT NULL COMMENT 'RT/RW: isian bebas',
    `kelurahan` varchar(50) DEFAULT NULL COMMENT 'Kelurahan/Desa: isian bebas',
    `kecamatan` varchar(50) DEFAULT NULL COMMENT 'Kecamatan: Isian bebas',
    `kabupaten_id` int(11) unsigned DEFAULT NULL COMMENT 'Kabupaten/Kota: merujuk ke tabel kabupaten kolom id',
    `kabupaten` varchar(50) DEFAULT NULL COMMENT 'Kabupaten/Kota: merujuk ke tabel kabupaten kolom nama(by system)',
    `propinsi_id` int(11) unsigned DEFAULT NULL COMMENT 'Propinsi: merujuk ke tabel propinsi kolom id',
    `propinsi` varchar(50) DEFAULT NULL COMMENT 'Propinsi: merujuk ke tabel propinsi kolom nama(by system)',
    `telepon` varchar(50) DEFAULT NULL COMMENT 'Nomor telepon: isian bebas',
    `fax` varchar(50) DEFAULT NULL COMMENT 'Nomor Fax: isian bebas',
    `email` varchar(50) DEFAULT NULL COMMENT 'Alamat email: isan format email',
    `agama_id` int(11) unsigned DEFAULT NULL COMMENT 'Agama: merujuk ke tabel agama kolom id',
    `agama_nama` varchar(50) DEFAULT NULL COMMENT 'Nama Agama: merujuk ke tabel agama kolom nama(by system)',
    `status_kawin` char(1) DEFAULT NULL COMMENT 'Statu Kawin: diisi dengan Kawin/Belum Kawin',
    `pekerjaan` varchar(255) DEFAULT NULL COMMENT 'Pekerjaan: isian bebas',
    `pendidikan_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Tingkat Pendidikan Terakhir: merujuk ke tabel tingkat_pendidikan kolom id',
    `pendidikan` varchar(50) DEFAULT NULL COMMENT 'Pendidikan terakhir: merujuk ke tabel pendidikan kolom kode',
    `warga_negara_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Negara: merujuk ke tabel negara kolom id',
    `warga_negara` varchar(50) DEFAULT NULL COMMENT 'Warga Negara: merujuk ke tabel negara kolom nama (by system)',
    `nama_ayah` varchar(50) DEFAULT NULL COMMENT 'Nama Ayah: isian bebas',
    `nama_ibu` varchar(50) DEFAULT NULL COMMENT 'Nama ibu: isian bebas',
    `keterangan` varchar(255) DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `foto` blob,
    `difabel` char(1) NOT NULL DEFAULT 'T' COMMENT 'Y=Ya, T = Tidak',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `nama` (`nama`),
    KEY `jenis_pihak_id` (`jenis_pihak_id`),
    KEY `kabupaten_id` (`kabupaten_id`),
    KEY `agama_id` (`agama_id`),
    KEY `warga_negara_id` (`warga_negara_id`),
    KEY `pendidikan_id` (`pendidikan_id`),
    CONSTRAINT `pihak_fk` FOREIGN KEY (`jenis_pihak_id`) REFERENCES `jenis_pihak` (`id`),
    CONSTRAINT `pihak_fk1` FOREIGN KEY (`kabupaten_id`) REFERENCES `kabupaten` (`id`),
    CONSTRAINT `pihak_fk2` FOREIGN KEY (`agama_id`) REFERENCES `agama` (`id`),
    CONSTRAINT `pihak_fk3` FOREIGN KEY (`warga_negara_id`) REFERENCES `negara` (`id`),
    CONSTRAINT `pihak_fk4` FOREIGN KEY (`pendidikan_id`) REFERENCES `tingkat_pendidikan` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 37466 DEFAULT CHARSET = latin1 AVG_ROW_LENGTH = 537 COMMENT = 'Data Para Pihak'

CREATE TABLE `perkara_penetapan` (
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key: (by system)',
    `jenis_acara` char(1) DEFAULT NULL COMMENT '1.Acara Cepat 2.Acara Biasa',
    `penetapan_majelis_hakim` date DEFAULT NULL COMMENT 'Tanggal Penetapan Majeis Hakim: isian tanggal',
    `nomor_sk_penetapan_majelis_hakim` varchar(50) DEFAULT '' COMMENT 'Nomor SK Penetapan Majelis Hakim: isian bebas',
    `sk_penetapan_majelis_hakim_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen SK Penetapan Majelis Hakim: form upload',
    `majelis_hakim_id` varchar(50) DEFAULT NULL COMMENT 'Id Hakim: dipisahkan dengan koma (by system)',
    `majelis_hakim_kode` varchar(100) DEFAULT NULL COMMENT 'Kode Hakim: dipisahkan oleh koma (by system)',
    `majelis_hakim_nama` varchar(500) DEFAULT NULL COMMENT 'Nama Hakim: dipisahkan dengan <br /> (by system)',
    `majelis_hakim_text` varchar(500) DEFAULT '' COMMENT 'View HTML Jabatan dan Nama Majelis Hakim (by system)',
    `penetapan_panitera_pengganti` date DEFAULT NULL COMMENT 'Tanggal Penetapan Panitera Pengganti: isian tanggal',
    `nomor_sk_penetapan_panitera_pengganti` varchar(50) DEFAULT NULL COMMENT 'Nomor SK penetapan Panitera Pengganti: isian bebas',
    `sk_penetapan_panitera_pengganti_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen SK Penetapan Panitera Pengganti: form upload',
    `panitera_pengganti_id` varchar(50) DEFAULT NULL COMMENT 'Id Panitera: dipisahkan dengan koma merujuk ke tabel perkara_panitera (by system)',
    `panitera_pengganti_text` varchar(500) DEFAULT '' COMMENT 'Nama Panitera Pengganti: dipisahkan dengan <br /> merujuk ke tabel perkara_panitera',
    `penetapan_jurusita` date DEFAULT NULL COMMENT 'Tanggal Penetapan Jurusita: isian tanggal',
    `nomor_sk_penetapan_jurusita` varchar(50) DEFAULT NULL COMMENT 'Nomor SK Penetapan Jurusita: isian bebas',
    `sk_penetapan_jurusita_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen SK Penetapan Jurusita: form upload',
    `jurusita_id` varchar(50) DEFAULT NULL COMMENT 'Id Jurusita: dipisahkan dengan koma yang merujuk ke tabel perkara_jurusita (by system)',
    `jurusita_text` varchar(500) DEFAULT '' COMMENT 'Nama Jurusita: dipisahkan dengan <br />\r\nmerujuk ke tabel perkara_jurusita(generate by system)',
    `penetapan_hari_sidang` date DEFAULT NULL COMMENT 'Tanggal Penetapan Hari Sidang: isian tanggal',
    `sidang_pertama` date DEFAULT NULL COMMENT 'Tanggal Sidang Pertama: merujuk ke tabel jadwal_sidang (by system)',
    `catatan_penetapan` longtext CHARACTER SET utf8mb4,
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`perkara_id`),
    KEY `penetapan_majelis_hakim` (`penetapan_majelis_hakim`),
    KEY `majelis_hakim_nama` (`majelis_hakim_nama`),
    KEY `majelis_hakim_kode` (`majelis_hakim_kode`),
    KEY `penetapan_panitera_pengganti` (
        `penetapan_panitera_pengganti`
    ),
    KEY `panitera_pengganti_text` (`panitera_pengganti_text`),
    KEY `penetapan_jurusita` (`penetapan_jurusita`),
    KEY `penetapan_hari_sidang` (`penetapan_hari_sidang`),
    CONSTRAINT `perkara_penetapan_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Penetapan Perkara'

CREATE TABLE `dirput_dokumen` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) NOT NULL,
    `dokumen_ref_id` bigint(20) NOT NULL,
    `filename` varchar(255) NOT NULL,
    `path_filename` varchar(355) NOT NULL,
    `created_by` varchar(255) NOT NULL,
    `created_date` date NOT NULL,
    `updated_by` varchar(255) DEFAULT NULL,
    `updated_date` date DEFAULT NULL,
    `pihak_detil_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'merujuk ke tabel banding_detil, kasasi_detil, pk_detil pada kolom id',
    `keterangan` varchar(255) DEFAULT NULL,
    `flag_sync` tinyint(1) DEFAULT NULL COMMENT 'penanda antrian sudah terupload atau belum',
    `pengajuan_id` tinyint(1) unsigned NOT NULL COMMENT '1 = tidak diajukan, 2 = banding, 3 = kasasi, 4 = pk, 5 = grasi',
    `published` tinyint(1) DEFAULT '0' COMMENT '0 = tidak dipublished, 1 = di published',
    `link_dirput` varchar(255) DEFAULT NULL,
    PRIMARY KEY (
        `perkara_id`,
        `dokumen_ref_id`,
        `pihak_detil_id`,
        `pengajuan_id`
    ),
    KEY `id` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 22971 DEFAULT CHARSET = latin1 COMMENT = 'Dokumen Dirput'

