CREATE TABLE `perkara` (
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `jenis_acara` char(1) DEFAULT NULL,
    `alur_perkara_id` int(11) unsigned NOT NULL COMMENT 'Id Alur Perkara: merujuk ke tabel alur_perkara kolom id(by system)',
    `tanggal_pendaftaran` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran: isian tanggal',
    `jenis_perkara_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Jenis Perkara: merujuk ke tabel jenis_perkara kolom id',
    `jenis_perkara_kode` varchar(20) DEFAULT '' COMMENT 'Kode Jenis Perkara: merujuk ke tabel jenis_perkara kolom kode (by system)',
    `jenis_perkara_nama` varchar(100) DEFAULT '' COMMENT 'Nama Jenis Perkara: merujuk ke tabel jenis_perkara kolom nama (by system)',
    `jenis_perkara_text` varchar(400) DEFAULT '' COMMENT 'Nama Jenis Perkara lengkap dengan induk perkaranya(by system)',
    `nomor_urut_register` int(11) unsigned DEFAULT NULL COMMENT 'Nomor Urut Buku Register: Reset per bulan',
    `nomor_urut_perkara` int(11) unsigned DEFAULT NULL COMMENT 'Nomor Urut Perkara: reset per tahun untuk tiap alur_perkara_id (manual/by system)',
    `nomor_perkara` varchar(250) NOT NULL COMMENT 'Nomor Perkara: (manual/by system)',
    `nomor_indeks` varchar(250) DEFAULT NULL COMMENT 'Nomor Indeks Perkara: untuk keperluan pengurutan data berdasarkan tahun,alur perkara dan nomor urut perkara (by system)',
    `tanggal_surat` date DEFAULT NULL COMMENT 'Tanggal Surat Gugatan/Permohonan/Pelimpahan: isian tanggal',
    `nomor_surat` varchar(150) DEFAULT '' COMMENT 'Nomor Surat Gugatan/Permohonan/Pelimpahan: isian bebas',
    `surat_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Surat Gugatan/Permohonan/Pelimpahan: form upload',
    `pihak1_text` longtext COMMENT 'Penggugat/Pemohon/Penuntut: (by system)',
    `pengacara_pihak1` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak2_text` longtext COMMENT 'Tergugat/Termohon/Terdakwa: (by system)',
    `pengacara_pihak2` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak3_text` longtext COMMENT 'Pihak Ke Tiga yang melakukan Intervensi: (by system)',
    `pengacara_pihak3` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak4_text` longtext,
    `pengacara_pihak4` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `para_pihak` longtext,
    `pihak_dipublikasikan` char(1) DEFAULT 'Y' COMMENT 'Para Pihak Dipublikasikan: pilihan(Y=Ya; T=Tidak)',
    `posita` longtext CHARACTER SET utf8mb4,
    `petitum` longtext CHARACTER SET utf8mb4,
    `petitum_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Petitum: form upload',
    `nomor_dakwaan` varchar(150) DEFAULT NULL,
    `tanggal_dakwaan` date DEFAULT NULL,
    `dakwaan` longtext CHARACTER SET utf8mb4,
    `pasal_dakwaan` longtext,
    `dakwaan_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Dakwaan: form upload',
    `tanggal_rencana_perdamaian` date DEFAULT NULL COMMENT 'Tanggal Penerimaan Rencana Perdamaian: isian tanggal',
    `tanggal_pengesahan_perdamaian` date DEFAULT NULL COMMENT 'Tanggal Pengesahan Perdamaian: isian tanggal',
    `tanggal_penyelesaian_mediasi` date DEFAULT NULL COMMENT 'Tanggal Penyelesaian Mediasi: isian tanggal',
    `tanggal_penyelesaian_konsiliasi` date DEFAULT NULL COMMENT 'Tanggal Penyelesaian Konsiliasi: isian tanggal',
    `perkara_rujukan_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara Rujukan: merujuk ke tabel perkara kolom perkara_id',
    `nomor_perkara_rujukan` varchar(50) DEFAULT '' COMMENT 'Nomor Perkara yang menjadi rujukan: merujuk ke tabel perkara kolom nomor_perkara (by system)',
    `tanggal_pendaftaran_rujukan` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran Rujukan: merujuk ke tabel perkara kolom tanggal_pendaftaran (by system)',
    `catatan_pendaftaran` text COMMENT 'Catatan Pendaftaran: isian bebas',
    `prodeo` tinyint(1) DEFAULT '0' COMMENT 'Status Prodeo: 0=Tidak,1:Ya',
    `terdakwa_anak` tinyint(1) DEFAULT '0' COMMENT 'Terdakwa Anak-Anak: 0 Tidak 1=Ya',
    `tahapan_terakhir_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Tahapan Proses: merujuk ke tabel tahapan_proses kolom id (by system)',
    `tahapan_terakhir_text` varchar(50) DEFAULT '' COMMENT 'Nama Tahapan Terakhir: merujuk ke tabel tahapan_proses kolom nama (by system)',
    `proses_terakhir_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Proses Perkara Terakhir: menujuk ke tabel proses kolom id (by system)',
    `proses_terakhir_text` varchar(200) DEFAULT '' COMMENT 'Proses Perkara Terakhir: menujuk ke tabel proses kolom Nama(by system)',
    `nilai_sengketa` bigint(20) unsigned DEFAULT '0',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT '' COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT '' COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`perkara_id`),
    UNIQUE KEY `nomor_perkara` (`nomor_perkara`),
    KEY `jenis_perkara_id` (`jenis_perkara_id`),
    KEY `nomor_indeks` (`nomor_indeks`),
    KEY `alur_perkara_id` (`alur_perkara_id`),
    KEY `tanggal_pendaftaran` (`tanggal_pendaftaran`),
    KEY `tahapan_terakhir_id` (`tahapan_terakhir_id`),
    KEY `proses_terakhir_id` (`proses_terakhir_id`),
    KEY `diinput_tanggal` (`diinput_tanggal`),
    KEY `diperbaharui_tanggal` (`diperbaharui_tanggal`),
    CONSTRAINT `perkara_fk` FOREIGN KEY (`alur_perkara_id`) REFERENCES `alur_perkara` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Induk Perkara'

CREATE TABLE `perkara_jurusita` (
    `id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (generate by system)',
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Id Perkara merujuk ke tabel perkara',
    `general_id` bigint(20) DEFAULT '0',
    `tahapan_id` tinyint(4) NOT NULL DEFAULT '10' COMMENT 'Mengacu ke Table Tahapan',
    `tanggal_penetapan` date DEFAULT NULL COMMENT 'Tanggal penetapan',
    `nomor_sk_penetapan` varchar(50) DEFAULT '' COMMENT 'Nomor SK Penetapan: isian bebas',
    `urutan` int(11) unsigned DEFAULT '1' COMMENT 'Urutan: by(system)',
    `jurusita_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Jurusita: merujuk ke tabel jurusita kolom id',
    `jurusita_kode` varchar(20) DEFAULT '' COMMENT 'Kode Jurusita: merujuk ke tabel jurusitakolom kode (by system)',
    `jurusita_nip` varchar(20) DEFAULT '' COMMENT 'NIP Jurusita: merujuk ke tabel jurusita kolom nip (by system)',
    `jurusita_nama` varchar(50) DEFAULT '' COMMENT 'Nama jurusita: merujuk ke tabel jurusita kolom nama (by system)',
    `diganti_oleh_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Jurusita Pengganti: merujuk ke tabel jurusita kolom id',
    `aktif` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Status Aktif: pilihan Y=Ya; T=Tidak',
    `tanggal_tidak_aktif` date DEFAULT NULL COMMENT 'Tanggal Tidak Aktif: isian tanggal',
    `keterangan` varchar(500) DEFAULT '' COMMENT 'Keterangan: isian bebas',
    `diinput_oleh` varchar(30) DEFAULT '' COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT '' COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `perkara_id` (`perkara_id`),
    KEY `jurusita_id` (`jurusita_id`),
    KEY `jurusita_nama` (`jurusita_nama`),
    KEY `aktif` (`aktif`),
    CONSTRAINT `perkara_jurusita_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_jurusita_fk1` FOREIGN KEY (`jurusita_id`) REFERENCES `jurusita` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Jurusita Perkara'

CREATE TABLE `perkara_panitera_pn` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key: (by system)',
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id',
    `tahapan_id` tinyint(4) NOT NULL DEFAULT '10' COMMENT 'Mengacu ke Table Tahapan',
    `tanggal_penetapan` date DEFAULT NULL COMMENT 'Tanggal Penetapan:isian tanggal',
    `nomor_sk_penetapan` varchar(50) DEFAULT NULL COMMENT 'Nomor SK Penetapan: isian bebas',
    `urutan` int(11) unsigned DEFAULT '1' COMMENT 'Urutan: (by system)',
    `panitera_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Panitera: merujuk ke tabel panitera_pn kolom id',
    `panitera_kode` varchar(20) DEFAULT NULL COMMENT 'Kode Panitera: merujuk ke tabel panitera_pn kolom kode (by system)',
    `panitera_nip` varchar(20) DEFAULT NULL COMMENT 'NIP Panitera: merujuk ke tabel panitera_pn kolom nip (by system)',
    `panitera_nama` varchar(50) DEFAULT NULL COMMENT 'Nama Panitera: merujuk ke tabel panitera_pn kolom nama (by system)',
    `diganti_oleh_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Panitera Pengganti: merujuk ke tabel panitera_pn kolom id',
    `aktif` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Status Aktif: pilihan Y=Ya; T=Tidak',
    `tanggal_tidak_aktif` date DEFAULT NULL COMMENT 'Tanggal Tidak Aktif: isian tanggal',
    `keterangan` varchar(500) DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `perkara_id` (`perkara_id`),
    KEY `panitera_id` (`panitera_id`),
    KEY `panitera_nama` (`panitera_nama`),
    KEY `panitera_kode` (`panitera_kode`),
    KEY `aktif` (`aktif`),
    CONSTRAINT `perkara_panitera_pn_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_panitera_pn_fk1` FOREIGN KEY (`panitera_id`) REFERENCES `panitera_pn` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 9739 DEFAULT CHARSET = latin1 COMMENT = 'Data Panitera Pengganti Perkara di Pengadilan Negeri'

CREATE TABLE `perkara_pihak1` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id(by system)',
    `urutan` int(11) unsigned DEFAULT NULL COMMENT 'Urutan: disi dengan bilangan',
    `pihak_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Pihak: merujuk ke tabel pihak kolom id',
    `jenis_pihak_id` tinyint(1) unsigned DEFAULT NULL COMMENT 'Id Jenis Pihak: merujuk ke tabel pihak kolom jenis_pihak_id(by system)',
    `nama` varchar(500) DEFAULT NULL COMMENT 'Nama: merujuk ke tabel pihak kolom nama(by system)',
    `alamat` varchar(500) DEFAULT NULL,
    `keterangan` varchar(255) DEFAULT NULL COMMENT 'Keterangan: Isian bebas',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaiki Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaiki Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `nama` (`nama`),
    KEY `perkara_id` (`perkara_id`),
    KEY `pihak_id` (`pihak_id`),
    CONSTRAINT `perkara_pihak1_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_pihak1_fk1` FOREIGN KEY (`pihak_id`) REFERENCES `pihak` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 13034 DEFAULT CHARSET = latin1 COMMENT = 'Data Pihak Pertama(Penggugat/Pemohon/Penuntut)'

CREATE TABLE `perkara_pihak2` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id(by system)',
    `urutan` int(11) unsigned DEFAULT NULL COMMENT 'Urutan: disii dengan bilangan',
    `pihak_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Pihak: merujuk ke tabel pihak',
    `jenis_pihak_id` tinyint(1) unsigned DEFAULT NULL COMMENT 'Id Jenis Pihak: merujuk ke tabel pihak kolom jenis_pihak_id(by system)',
    `nama` varchar(500) DEFAULT NULL COMMENT 'Nama: merujuk ke tabel pihak kolom nama(by system)',
    `alamat` varchar(500) DEFAULT NULL,
    `keterangan` varchar(255) DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `pangkat` varchar(100) DEFAULT NULL,
    `nrp` varchar(50) DEFAULT NULL,
    `jabatan` varchar(100) DEFAULT NULL,
    `kesatuan` varchar(100) DEFAULT NULL,
    `ditahan_oleh_id` int(11) unsigned DEFAULT NULL COMMENT 'Ditahan Oleh (terakhir): merujuk ke tabel penahan_terdakwa (by system)',
    `status_penahanan_id` tinyint(4) unsigned DEFAULT NULL COMMENT 'Status Penahanan (terakhir): merujuk ke tabel status_penahanan kolom id(by system)',
    `jenis_tahanan_id` tinyint(4) unsigned DEFAULT NULL COMMENT 'Jenis Tahanan (terakhir): merujuk ke tabel jenis_tahanan kolom id (by system)',
    `ghaib` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Apakah pihak tidak diketahui alamatnya? 1(ya), 0(tidak)',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput oleh(by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput tanggal(by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaiki oleh(by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaiki tanggal(by system)',
    PRIMARY KEY (`id`),
    KEY `nama` (`nama`),
    KEY `perkara_id` (`perkara_id`),
    KEY `pihak_id` (`pihak_id`),
    CONSTRAINT `perkara_pihak2_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_pihak2_fk1` FOREIGN KEY (`pihak_id`) REFERENCES `pihak` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 6343 DEFAULT CHARSET = latin1 COMMENT = 'Data Pihak Kedua(Tergugat/Termohon/Terdakwa)'

CREATE TABLE `perkara_jadwal_sidang` (
    `id` bigint(20) unsigned NOT NULL COMMENT 'Primary key: (by system)',
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id',
    `verzet` char(1) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT 'T' COMMENT 'flag untuk sidang verzet/biasa (by system)',
    `keberatan` char(1) DEFAULT 'T' COMMENT 'flag untuk sidang perkara keberatan',
    `ikrar_talak` char(1) DEFAULT 'T',
    `urutan` int(11) unsigned NOT NULL DEFAULT '1' COMMENT 'Urutan Jadwal Sidang Salam Satu Hari yang sama: (by system)',
    `tanggal_sidang` date NOT NULL COMMENT 'Tanggal Sidang: isian tanggal',
    `jam_sidang` time DEFAULT NULL COMMENT 'Mulai Jam Sidang: isian format jam:menit',
    `sampai_jam` time DEFAULT NULL COMMENT 'Sampai Jam Sidang : isian format jam:menit',
    `agenda_id` varchar(50) DEFAULT NULL COMMENT 'Agenda Sidang : merujuk ke tabel agenda_sidang dengan pemisah koma',
    `agenda` varchar(500) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Agenda Sidang: isian bebas',
    `ruangan_id` int(11) unsigned DEFAULT NULL COMMENT 'id Ruangan Sidang: merujuk ke tabel ruangan_sidang kolom id',
    `ruangan` varchar(50) DEFAULT NULL COMMENT 'Ruangan Sidang: merujuk ke tabel ruangan_sidang kolom nama (by system)',
    `sidang_keliling` char(1) DEFAULT 'T' COMMENT 'Y dan T',
    `dihadiri_oleh` tinyint(3) DEFAULT NULL,
    `ditunda` char(1) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT 'T' COMMENT 'Sidang Ditunda: pilihan Y=Ya; T=Tidak',
    `alasan_ditunda` varchar(500) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Alasan Ditunda: isian bebas',
    `sidang_ditempat` tinyint(1) DEFAULT '0' COMMENT 'Sidang Di Tempat: 0=Tidak, 1=Ya',
    `sifat_sidang` char(1) DEFAULT 'Y' COMMENT 'Y: Dibuka Untuk Umum, T: Tertutup Untuk Umum',
    `keterangan` varchar(500) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `edoc_bas` varchar(250) DEFAULT NULL,
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `verzet` (`verzet`),
    KEY `perkara_id` (`perkara_id`),
    KEY `ruangan_id` (`ruangan_id`),
    KEY `tanggal_sidang` (`tanggal_sidang`),
    KEY `jam_sidang` (`jam_sidang`),
    CONSTRAINT `perkara_jadwal_sidang_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_jadwal_sidang_fk1` FOREIGN KEY (`ruangan_id`) REFERENCES `ruangan_sidang` (`id`) ON DELETE SET NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Jadwal Pesidangan'

CREATE TABLE `perkara_putusan` (
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `tanggal_putusan` date NOT NULL,
    `putusan_verstek` varchar(1) DEFAULT NULL COMMENT 'Putusan Verstek: pilihan Y=Ya; T=Tidak',
    `sumber_hukum_id` varchar(20) DEFAULT NULL COMMENT 'Diputus Dengan: pilihan (KUH Perdata,KUH Dagang, Adat, UU/PP)',
    `status_putusan_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Status Putusan: merujuk ke tabel status_putusan kolom id',
    `status_putusan_kode` varchar(20) DEFAULT NULL COMMENT 'Kode Status Putusan: merujuk ke tabel status putusan kolom kode (by system)',
    `status_putusan_nama` varchar(100) DEFAULT NULL COMMENT 'Nama Status Putusan: merujuk ke tabel status_putusan kolom nama (by system)',
    `status_putusan_text` varchar(5000) DEFAULT '' COMMENT 'Keterangan Putusan: (by system)',
    `tanggal_cabut` date DEFAULT NULL COMMENT 'Tanggal Cabut, jika status putusan dicabut(status_putusan_id=7)',
    `tanggal_gugur` date DEFAULT NULL COMMENT 'Tanggal Gugur: jika status putusan gugur(status_putusan_id=6)',
    `amar_putusan` longtext CHARACTER SET utf8mb4,
    `amar_putusan_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen Amar Putusan: form upload',
    `amar_putusan_anonimisasi_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen Amar Putusan Anonimisasi: form upload',
    `penetapan_hakim_pengawas` date DEFAULT NULL COMMENT 'Tanggal Penetapan Hakim Pengawas: isian tanggal',
    `nomor_penetapan_hakim_pengawas` varchar(50) DEFAULT NULL COMMENT 'Nomor Penetapan Hakim Pengawas',
    `hakim_pengawas_id` varchar(50) DEFAULT NULL COMMENT 'Id Hakim Pengawas: dipisahkan dengan koma',
    `pengurus_id` varchar(50) DEFAULT NULL COMMENT 'Id Pengurus: dipisahkan dengan koma',
    `tanggal_penetapan_kreditur` date DEFAULT NULL COMMENT 'Tanggal Penetapan Panitia Kreditur: isian tanggal',
    `panitia_kreditur` varchar(500) DEFAULT NULL COMMENT 'Panitia Kreditur: isian bebas',
    `kurator_id` varchar(50) DEFAULT NULL COMMENT 'Id Kurator: dipisahkan dengan koma',
    `tanggal_berita_putusan` date DEFAULT NULL COMMENT 'Tanggal Pengumuman Dalam Berita Negara RI: isian tanggal',
    `nama_media_berita_putusan` varchar(250) DEFAULT NULL COMMENT 'Nama Media Berita: isian bebas',
    `tanggal_surat_kabar_putusan` date DEFAULT NULL COMMENT 'Tanggal Pengumuman Dalam Surat Kabar: isian tanggal',
    `nama_surat_kabar_putusan` varchar(250) DEFAULT NULL COMMENT 'Nama Surat Kabar: isian bebas',
    `tanggal_minutasi` date DEFAULT NULL COMMENT 'Tanggal Minutasi: isian tanggal',
    `pemberitahuan_putusan` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada para Pihak: isian tanggal',
    `pemberitahuan_putusan_pihak1` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada Pihak Penggugat/Pemohon/JPU: isian tanggal',
    `pemberitahuan_putusan_pihak2` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada Pihak Tergugat/Termohon/Terdakwa: isian tanggal',
    `pemberitahuan_putusan_pihak3` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada Pihak Intervensi: isian tanggal',
    `pemberitahuan_putusan_ankum` date DEFAULT NULL,
    `pemberitahuan_putusan_pepera` date DEFAULT NULL,
    `menerima_putusan_pihak1` date DEFAULT NULL COMMENT 'Tanggal JPU menerima putusan: isian tanggal',
    `menerima_putusan_pihak2` date DEFAULT NULL COMMENT 'Tanggal Terdakwa Menerima Putusan: isian tanggal',
    `penerbitan_salinan_putusan` date DEFAULT NULL COMMENT 'Tanggal Penerbitan Salinan Putusan',
    `kirim_salinan_putusan_pihak1` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada JPU: isian tanggal',
    `kirim_salinan_putusan_pihak2` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada Terdakwa: isian tanggal',
    `kirim_salinan_putusan_pihak3` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada Pihak Intervensi: isian tanggal',
    `kirim_salinan_putusan_penyidik` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada Penyidik: isian tanggal',
    `catatan_putusan` longtext CHARACTER SET utf8mb4,
    `nilai_ganti_kerugian` bigint(20) DEFAULT NULL,
    `tanggal_bht` date DEFAULT NULL,
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (
        `perkara_id`,
        `tanggal_putusan`
    ),
    KEY `tanggal_putusan` (`tanggal_putusan`),
    KEY `tanggal_cabut` (`tanggal_cabut`),
    KEY `tanggal_gugur` (`tanggal_gugur`),
    KEY `putusan_verstek` (`putusan_verstek`),
    KEY `status_putusan_id` (`status_putusan_id`),
    KEY `tanggal_minutasi` (`tanggal_minutasi`),
    CONSTRAINT `perkara_putusan_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Putusan Perkara'